FROM ubuntu

MAINTAINER <chenyiyanggermany@gmail.com>

RUN apt-get update && apt-get install nodejs -y && apt-get install npm -y

WORKDIR /usr/local/bin/

# COPY main.js .

CMD ["/bin/bash"]
